<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectsSeeder extends Seeder
{
    /**
     * IMPORTANT: target_amount / raised_amount / beneficiaries_count below are
     * PLACEHOLDER figures. Project names, descriptions, and locations are sourced
     * from Mutrahimeen's own official profile document (33-page organizational
     * profile, references page listing real activity since 2018). Replace the
     * financial figures with real internal numbers before going live.
     */
    public function run(): void
    {
        $categories = DB::table('project_categories')->pluck('id', 'name_ar');

        $medical    = $categories['المجال الطبي'] ?? 1;
        $seasonal   = $categories['الإغاثة الموسمية'] ?? 2;
        $emergency  = $categories['الطوارئ ودعم النازحين'] ?? 3;
        $income     = $categories['التمكين الاقتصادي'] ?? 4;
        $religious  = $categories['البرامج الدينية والتعليمية'] ?? 5;

        $projects = [
            [
                'id'                    => 1,
                'category_id'           => $seasonal,
                'title_ar'              => 'الحقيبة الرمضانية',
                'title_en'              => 'Ramadan Basket',
                'short_description_ar'  => 'كل زاد يصل بيت هو راحة أم سهرت همًا. توزيع سلال غذائية أساسية للعائلات المحتاجة خلال شهر رمضان.',
                'short_description_en'  => 'Every provision that reaches a home is relief for a mother who stayed up worrying. Distributing essential food baskets to families in need during Ramadan.',
                'full_description_ar'   => 'من أعرق مشاريعنا الموسمية، مستمر منذ عام 2018 وحتى اليوم دون انقطاع. نوزع سلال غذائية أساسية (زيت، دقيق، تمر وغيرها) للعائلات المحتاجة في أحياء الخرطوم خلال شهر رمضان المبارك.',
                'full_description_en'   => 'One of our longest-running seasonal projects, continuously active since 2018. We distribute essential food baskets — oil, flour, dates and more — to families in need across Khartoum neighborhoods throughout Ramadan.',
                'type'                  => 'seasonal',
                'status'                => 'active',
                'target_amount'         => 60000000.00,
                'raised_amount'         => 38000000.00,
                'beneficiaries_count'   => 3500,
                'location_ar'           => 'أحياء الخرطوم',
                'location_en'           => 'Khartoum Neighborhoods',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2018-05-01',
                'end_date'              => null,
                'is_featured'           => true,
                'is_active'             => true,
                'display_order'         => 1,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 2,
                'category_id'           => $medical,
                'title_ar'              => 'الأيام العلاجية والقوافل الطبية',
                'title_en'              => 'Medical Treatment Days & Convoys',
                'short_description_ar'  => 'في زمن يصعب فيه إيجاد الرعاية الصحية، يظفر شباب متراحمين بكل ما لديهم لإقامة أيام صحية وقوافل طبية.',
                'short_description_en'  => 'In a time when healthcare is hard to find, Mutrahimeen youth give everything they have to run treatment days and medical convoys.',
                'full_description_ar'   => 'قوافل وأيام طبية نفذت في الولاية الشمالية (الإراك، القرير، الكرفاب)، ولاية نهر النيل (بربر، العكد، معسكرات نازحي شندي)، ولاية الجزيرة (واصلة، المناقل)، وشرق السودان (حلفا الجديدة)، بالإضافة إلى أيام صحية في الخرطوم (السمرة، حي النسيم، الدروشاب، شرق النيل) وعطبرة (معسكر النهضة، امبكول)، بالشراكة أحياناً مع كليات طب وجهات صحية أخرى، وتشمل استشارات مجانية وتوفير أدوية ودعم مرضى بمبالغ لعمليات جراحية.',
                'full_description_en'   => 'Medical convoys and treatment days carried out in Northern State (Al-Irak, Al-Qarir, Al-Kirfab), River Nile State (Berber, Al-Akad, Shendi IDP camps), Al Jazirah State (Wasila, Al-Managil), and East Sudan (New Halfa), alongside health days in Khartoum (Al-Samra, Hai Al-Naseem, Al-Daroshab, East Nile) and Atbara (Al-Nahda camp, Umbakol) — sometimes in partnership with medical colleges, providing free consultations, medicine, and financial support for patient surgeries.',
                'type'                  => 'sustainable',
                'status'                => 'active',
                'target_amount'         => 90000000.00,
                'raised_amount'         => 41000000.00,
                'beneficiaries_count'   => 6200,
                'location_ar'           => 'عدة ولايات (الشمالية، نهر النيل، الجزيرة، كسلا)',
                'location_en'           => 'Multiple States (Northern, River Nile, Al Jazirah, Kassala)',
                'governorate'           => 'نهر النيل',
                'start_date'            => '2021-01-01',
                'end_date'              => null,
                'is_featured'           => true,
                'is_active'             => true,
                'display_order'         => 2,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 3,
                'category_id'           => $seasonal,
                'title_ar'              => 'إفطار عابر سبيل',
                'title_en'              => 'Iftar for Travelers',
                'short_description_ar'  => 'نزلتم سهلاً وحللتم أهلاً من مشروع إفطار عابر سبيل. وجبات إفطار للمحتاجين وعابري السبيل في رمضان.',
                'short_description_en'  => 'Welcome, from the Iftar for Travelers project — meals for those in need and travelers during Ramadan.',
                'full_description_ar'   => 'فرق تطوعية بسترات صفراء تنتشر عند تقاطعات الطرق الرئيسية في الخرطوم لتقديم وجبات إفطار للمحتاجين وعابري السبيل، مستمر منذ عام 2018.',
                'full_description_en'   => 'Volunteer teams in yellow vests spread across major road intersections in Khartoum to provide iftar meals to those in need and travelers, running since 2018.',
                'type'                  => 'seasonal',
                'status'                => 'active',
                'target_amount'         => 25000000.00,
                'raised_amount'         => 17500000.00,
                'beneficiaries_count'   => 4000,
                'location_ar'           => 'تقاطعات الطرق الرئيسية بالخرطوم',
                'location_en'           => 'Main Road Intersections in Khartoum',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2018-03-01',
                'end_date'              => null,
                'is_featured'           => false,
                'is_active'             => true,
                'display_order'         => 3,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 4,
                'category_id'           => $seasonal,
                'title_ar'              => 'موسم الأضاحي',
                'title_en'              => 'Qurbani Season',
                'short_description_ar'  => 'موسميًا نقدم مشروع الأضحية كأسمى صور التراحم. توفير لحوم الأضاحي للأسر الفقيرة في عيد الأضحى.',
                'short_description_en'  => 'Every season we offer the Qurbani project as the noblest expression of compassion. Providing sacrificial meat to poor families during Eid al-Adha.',
                'full_description_ar'   => 'توزيع لحوم الأضاحي على الأسر الفقيرة في عدة ولايات خلال موسم عيد الأضحى، بمشاركة متطوعين على الأرض في التقطيع والتوزيع المباشر.',
                'full_description_en'   => 'Distributing sacrificial meat to poor families across several states during the Eid al-Adha season, with volunteers on the ground handling cutting and direct distribution.',
                'type'                  => 'seasonal',
                'status'                => 'completed',
                'target_amount'         => 45000000.00,
                'raised_amount'         => 45000000.00,
                'beneficiaries_count'   => 2100,
                'location_ar'           => 'عدة ولايات',
                'location_en'           => 'Multiple States',
                'governorate'           => 'كسلا',
                'start_date'            => '2021-06-01',
                'end_date'              => '2021-07-05',
                'is_featured'           => false,
                'is_active'             => true,
                'display_order'         => 4,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 5,
                'category_id'           => $seasonal,
                'title_ar'              => 'كسوة الشتاء',
                'title_en'              => 'Winter Clothing Campaign',
                'short_description_ar'  => 'علينا أن نفصل بين الفرد والبرد، ففي كل شتاء هناك من لا مأوى لهم. توزيع الملابس الشتوية والبطانيات.',
                'short_description_en'  => 'We must stand between people and the cold — every winter, some have no shelter. Distributing winter clothes and blankets.',
                'full_description_ar'   => 'توزيع الملابس الشتوية والبطانيات على الأسر ذات الدخل المحدود والنازحين خلال فصل الشتاء، لحمايتهم من البرد القارس.',
                'full_description_en'   => 'Distributing winter clothing and blankets to low-income families and displaced people during the cold season, protecting them from harsh weather.',
                'type'                  => 'seasonal',
                'status'                => 'active',
                'target_amount'         => 30000000.00,
                'raised_amount'         => 12500000.00,
                'beneficiaries_count'   => 1800,
                'location_ar'           => 'عدة ولايات',
                'location_en'           => 'Multiple States',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2021-11-01',
                'end_date'              => null,
                'is_featured'           => true,
                'is_active'             => true,
                'display_order'         => 5,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 6,
                'category_id'           => $seasonal,
                'title_ar'              => 'كسوة العيد',
                'title_en'              => 'Eid Clothing for Children',
                'short_description_ar'  => 'إنما العيد للأطفال فرحة. توفير ملابس جديدة للأطفال المحتاجين قبيل العيد.',
                'short_description_en'  => 'Eid is, above all, joy for children. Providing new clothes for children in need ahead of Eid.',
                'full_description_ar'   => 'مشروع سنوي مستمر منذ 2018، نوزع فيه ملابس عيد جديدة على أطفال الأسر المحتاجة، بمشاركة فرق تطوعية لفرز وتغليف الملابس وتوزيعها بشكل مباشر.',
                'full_description_en'   => 'An annual project running since 2018, providing new Eid clothes to children of families in need, with volunteer teams sorting, wrapping, and distributing directly.',
                'type'                  => 'seasonal',
                'status'                => 'active',
                'target_amount'         => 20000000.00,
                'raised_amount'         => 9000000.00,
                'beneficiaries_count'   => 1500,
                'location_ar'           => 'أحياء الخرطوم',
                'location_en'           => 'Khartoum Neighborhoods',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2018-04-01',
                'end_date'              => null,
                'is_featured'           => false,
                'is_active'             => true,
                'display_order'         => 6,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 7,
                'category_id'           => $emergency,
                'title_ar'              => 'دعم نازحي الفاشر',
                'title_en'              => 'El Fasher Displacement Response',
                'short_description_ar'  => 'كانت فترة توافد نازحين الفاشر حاملة لأقسى مشاهد الإنسانية رعبًا. دعم فرش وأغطية للنازحين في المخيمات.',
                'short_description_en'  => 'The period of El Fasher displacement carried some of the harshest humanitarian scenes. Providing mats and covers for displaced families in camps.',
                'full_description_ar'   => 'استجابة طارئة لموجة نزوح كثيفة من مدينة الفاشر، حيث قامت فرق متراحمين بتوزيع الفرش والأغطية على العائلات النازحة في مخيمات الخيام، إلى جانب دعم مادي وعيني في بداية الحرب عام 2023.',
                'full_description_en'   => 'An emergency response to a heavy wave of displacement from El Fasher city, where Mutrahimeen teams distributed mats and covers to displaced families in tent camps, alongside material and in-kind support since the start of the war in 2023.',
                'type'                  => 'relief',
                'status'                => 'active',
                'target_amount'         => 50000000.00,
                'raised_amount'         => 21000000.00,
                'beneficiaries_count'   => 2800,
                'location_ar'           => 'مخيمات النازحين',
                'location_en'           => 'IDP Camps',
                'governorate'           => 'كسلا',
                'start_date'            => '2023-05-01',
                'end_date'              => null,
                'is_featured'           => true,
                'is_active'             => true,
                'display_order'         => 7,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 8,
                'category_id'           => $medical,
                'title_ar'              => 'دعم مراكز علاج الكوليرا',
                'title_en'              => 'Cholera Treatment Center Support',
                'short_description_ar'  => 'تفشي الأمراض في مجتمعنا حرب نخوضها جميعًا. دعم مراكز علاج الكوليرا بالدربات (المحاليل الوريدية) في الخرطوم.',
                'short_description_en'  => 'Disease outbreaks in our community are a battle we all fight together. Supporting cholera treatment centers with IV fluids in Khartoum.',
                'full_description_ar'   => 'دعم مراكز علاج مرضى الكوليرا بتوفير المحاليل الوريدية (الدربات) والمستلزمات الطبية الأساسية في الخرطوم، استجابة لتفشي الوباء في المجتمعات المتضررة.',
                'full_description_en'   => 'Supporting cholera treatment centers by providing IV fluids and essential medical supplies in Khartoum, in response to outbreaks affecting vulnerable communities.',
                'type'                  => 'relief',
                'status'                => 'active',
                'target_amount'         => 15000000.00,
                'raised_amount'         => 6000000.00,
                'beneficiaries_count'   => 900,
                'location_ar'           => 'الخرطوم',
                'location_en'           => 'Khartoum',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2024-08-01',
                'end_date'              => null,
                'is_featured'           => false,
                'is_active'             => true,
                'display_order'         => 8,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 9,
                'category_id'           => $income,
                'title_ar'              => 'تمليك المشاريع الصغيرة',
                'title_en'              => 'Small Business Ownership Projects',
                'short_description_ar'  => 'مشاريع صغيرة كبيرة في أعين مستحقيها. تمليك مشاريع دخل مستدامة للأسر المحتاجة.',
                'short_description_en'  => 'Small projects that are big in the eyes of those who deserve them. Granting ownership of sustainable income projects to families in need.',
                'full_description_ar'   => 'نمكّن الأسر المحتاجة اقتصاديًا عبر تمليكها مشاريع دخل صغيرة تدار ذاتيًا، مثل عربات الآيسكريم، مشاريع التبريد والتجميد، محلات الطعمية، مشاريع التجارة الصغيرة، وأكشاك الشاي، إلى جانب دعم أسر الأيتام بمواد تموينية ومساعدات مالية.',
                'full_description_en'   => 'We economically empower families in need by granting ownership of small, self-managed income projects — ice cream carts, refrigeration/freezing projects, falafel shops, small trading ventures, and tea stands — alongside supporting orphan families with provisions and financial aid.',
                'type'                  => 'sustainable',
                'status'                => 'active',
                'target_amount'         => 40000000.00,
                'raised_amount'         => 14000000.00,
                'beneficiaries_count'   => 65,
                'location_ar'           => 'الخرطوم',
                'location_en'           => 'Khartoum',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2022-01-01',
                'end_date'              => null,
                'is_featured'           => false,
                'is_active'             => true,
                'display_order'         => 9,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 10,
                'category_id'           => $religious,
                'title_ar'              => 'دعم الخلاوي القرآنية',
                'title_en'              => 'Quran School Support',
                'short_description_ar'  => 'لمن كان القرآن نورًا قلبه، لمن ستكون السعادة عنوان دربه. دعم طلاب الخلاوي بالمواد التموينية والوجبات.',
                'short_description_en'  => 'For those whose hearts are lit by the Quran, whose path leads to happiness. Supporting Quran school students with provisions and meals.',
                'full_description_ar'   => 'دعم طلاب الخلاوي القرآنية بالمواد التموينية والوجبات السريعة ومواد النظافة الشخصية والمصاحف، وزيارات ميدانية دورية من متطوعي متراحمين.',
                'full_description_en'   => 'Supporting Quran school (khalwa) students with food provisions, quick meals, personal hygiene supplies, and copies of the Quran, alongside regular field visits from Mutrahimeen volunteers.',
                'type'                  => 'sustainable',
                'status'                => 'active',
                'target_amount'         => 18000000.00,
                'raised_amount'         => 7500000.00,
                'beneficiaries_count'   => 600,
                'location_ar'           => 'الخرطوم',
                'location_en'           => 'Khartoum',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2022-01-01',
                'end_date'              => null,
                'is_featured'           => false,
                'is_active'             => true,
                'display_order'         => 10,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 11,
                'category_id'           => $religious,
                'title_ar'              => 'توزيع المصاحف',
                'title_en'              => 'Quran Distribution',
                'short_description_ar'  => 'تجري الأيام وتنقضي ويبقى الأثر حاضرًا شاهدًا. توزيع نسخ من القرآن الكريم على المساجد والخلاوي.',
                'short_description_en'  => 'Days pass, but the impact remains, a lasting witness. Distributing copies of the Quran to mosques and Quran schools.',
                'full_description_ar'   => 'توزيع نسخ من المصحف الشريف على المساجد ومراكز التوزيع والخلاوي القرآنية.',
                'full_description_en'   => 'Distributing copies of the Quran to mosques, distribution centers, and Quran schools.',
                'type'                  => 'seasonal',
                'status'                => 'active',
                'target_amount'         => 8000000.00,
                'raised_amount'         => 3200000.00,
                'beneficiaries_count'   => 400,
                'location_ar'           => 'مساجد وخلاوي الخرطوم',
                'location_en'           => 'Mosques & Quran Schools in Khartoum',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2023-01-01',
                'end_date'              => null,
                'is_featured'           => false,
                'is_active'             => true,
                'display_order'         => 11,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 12,
                'category_id'           => $religious,
                'title_ar'              => 'الحقيبة المدرسية',
                'title_en'              => 'School Bag Project',
                'short_description_ar'  => 'قائد الغد يدرس الآن. توفير حقائب وأدوات مدرسية للأطفال المحتاجين.',
                'short_description_en'  => "Tomorrow's leader is studying now. Providing school bags and supplies for children in need.",
                'full_description_ar'   => 'توفير حقائب مدرسية كاملة بأدواتها للأطفال المحتاجين قبيل بداية العام الدراسي، لضمان استمرارهم في التعليم دون عوائق مادية.',
                'full_description_en'   => 'Providing fully-equipped school bags to children in need ahead of the school year, ensuring their education continues without financial barriers.',
                'type'                  => 'seasonal',
                'status'                => 'active',
                'target_amount'         => 22000000.00,
                'raised_amount'         => 10000000.00,
                'beneficiaries_count'   => 1100,
                'location_ar'           => 'الخرطوم',
                'location_en'           => 'Khartoum',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2018-08-01',
                'end_date'              => null,
                'is_featured'           => false,
                'is_active'             => true,
                'display_order'         => 12,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
        ];

        DB::table('projects')->insert($projects);

        $projectMedia = [
            ['project_id' => 1,  'url' => 'https://images.unsplash.com/photo-1594708767771-a7502209ff51?auto=format&fit=crop&w=1200&q=80', 'caption_ar' => 'توزيع الحقائب الرمضانية', 'caption_en' => 'Distributing Ramadan baskets'],
            ['project_id' => 2,  'url' => 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80', 'caption_ar' => 'قافلة طبية ميدانية', 'caption_en' => 'A field medical convoy'],
            ['project_id' => 3,  'url' => 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=1200&q=80', 'caption_ar' => 'إفطار عابر سبيل عند تقاطعات الطرق', 'caption_en' => 'Iftar for travelers at road intersections'],
            ['project_id' => 4,  'url' => 'https://images.unsplash.com/photo-1607346256330-dee7af15f7c5?auto=format&fit=crop&w=1200&q=80', 'caption_ar' => 'توزيع لحوم الأضاحي', 'caption_en' => 'Distributing Qurbani meat'],
            ['project_id' => 5,  'url' => 'https://images.unsplash.com/photo-1608155918314-04a2b1f00889?auto=format&fit=crop&w=1200&q=80', 'caption_ar' => 'توزيع الملابس الشتوية', 'caption_en' => 'Distributing winter clothes'],
            ['project_id' => 6,  'url' => 'https://images.unsplash.com/photo-1607344645866-009c320b63e0?auto=format&fit=crop&w=1200&q=80', 'caption_ar' => 'كسوة العيد للأطفال', 'caption_en' => 'Eid clothing for children'],
            ['project_id' => 7,  'url' => 'https://images.unsplash.com/photo-1541943180-25783b78f6f8?auto=format&fit=crop&w=1200&q=80', 'caption_ar' => 'دعم النازحين في المخيمات', 'caption_en' => 'Supporting displaced families in camps'],
            ['project_id' => 8,  'url' => 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=1200&q=80', 'caption_ar' => 'دعم مراكز العلاج الصحي', 'caption_en' => 'Supporting health treatment centers'],
            ['project_id' => 9,  'url' => 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?auto=format&fit=crop&w=1200&q=80', 'caption_ar' => 'دعم مشاريع الدخل الصغيرة', 'caption_en' => 'Supporting small income projects'],
            ['project_id' => 10, 'url' => 'https://images.unsplash.com/photo-1585036156171-384164a8c675?auto=format&fit=crop&w=1200&q=80', 'caption_ar' => 'دعم طلاب الخلاوي', 'caption_en' => 'Supporting Quran school students'],
            ['project_id' => 11, 'url' => 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=1200&q=80', 'caption_ar' => 'توزيع المصاحف', 'caption_en' => 'Distributing copies of the Quran'],
            ['project_id' => 12, 'url' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80', 'caption_ar' => 'توزيع الحقائب المدرسية', 'caption_en' => 'Distributing school bags'],
        ];

        foreach ($projectMedia as $i => $media) {
            DB::table('project_media')->insert([
                'project_id'    => $media['project_id'],
                'media_type'    => 'image',
                'url'           => $media['url'],
                'caption_ar'    => $media['caption_ar'],
                'caption_en'    => $media['caption_en'],
                'is_cover'      => true,
                'display_order' => 1,
            ]);
        }
    }
}