<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectsSeeder extends Seeder
{
    public function run(): void
    {
        $categories = DB::table('project_categories')->pluck('id', 'name_ar');

        $medical   = $categories['المجال الطبي'] ?? 1;
        $training  = $categories['التدريب والتطوير'] ?? 2;
        $income    = $categories['مشاريع الدخل الثابت'] ?? 3;
        $seasonal  = $categories['البرامج الخيرية الموسمية'] ?? 4;
        $meals     = $categories['توزيع الوجبات والإفطار'] ?? 5;

        $projects = [
            [
                'id'                    => 1,
                'category_id'           => $seasonal,
                'title_ar'              => 'الحقيبة الرمضانية',
                'title_en'              => 'Ramadan Basket',
                'short_description_ar'  => 'توزيع سلال غذائية أساسية للعائلات المحتاجة خلال شهر رمضان.',
                'short_description_en'  => 'Distributing essential food baskets to families in need during Ramadan.',
                'full_description_ar'   => 'توزيع سلال غذائية أساسية للعائلات المحتاجة خلال شهر رمضان، لتوفير احتياجاتهم ودعمهم في تلبية متطلبات الشهر الفضيل من زيت ودقيق وتمر وغيرها من المواد الأساسية.',
                'full_description_en'   => 'We distribute essential food baskets — oil, flour, dates and more — to families in need throughout the holy month of Ramadan, helping them meet their needs during this blessed time.',
                'type'                  => 'seasonal',
                'status'                => 'active',
                'target_amount'         => 60000000.00,
                'raised_amount'         => 38000000.00,
                'beneficiaries_count'   => 3500,
                'location_ar'           => 'أحياء الخرطوم',
                'location_en'           => 'Khartoum Neighborhoods',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2024-02-01',
                'end_date'              => null,
                'is_featured'           => true,
                'is_active'             => true,
                'display_order'         => 1,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 2,
                'category_id'           => $medical,
                'title_ar'              => 'القوافل الطبية',
                'title_en'              => 'Medical Convoys',
                'short_description_ar'  => 'قوافل طبية متنقلة تقدم استشارات وأدوية مجانية للمجتمعات المحرومة.',
                'short_description_en'  => 'Mobile medical convoys offering free consultations and medicine to underserved communities.',
                'full_description_ar'   => 'توفير خدمات الرعاية الصحية الأساسية من خلال القوافل الطبية المتنقلة وأيام العلاج والحملات التثقيفية، وتحسين الوصول إلى الرعاية الصحية الجيدة للمجتمعات المحرومة عبر ولايات السودان المختلفة.',
                'full_description_en'   => 'We provide essential healthcare services through mobile medical convoys, treatment days, and awareness campaigns, improving access to quality healthcare for underserved communities across Sudan.',
                'type'                  => 'sustainable',
                'status'                => 'active',
                'target_amount'         => 90000000.00,
                'raised_amount'         => 41000000.00,
                'beneficiaries_count'   => 6200,
                'location_ar'           => 'مناطق متفرقة',
                'location_en'           => 'Various Areas',
                'governorate'           => 'الجزيرة',
                'start_date'            => '2023-05-01',
                'end_date'              => null,
                'is_featured'           => true,
                'is_active'             => true,
                'display_order'         => 2,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 3,
                'category_id'           => $meals,
                'title_ar'              => 'إفطار عابر السبيل',
                'title_en'              => 'Iftar for Travelers',
                'short_description_ar'  => 'تقديم وجبات إفطار للمحتاجين وعابري السبيل خلال شهر رمضان المبارك.',
                'short_description_en'  => 'Providing iftar meals to travelers and people in need during Ramadan.',
                'full_description_ar'   => 'تقديم وجبات غذائية للمحتاجين وعابري السبيل، لضمان حصولهم على طعام مغذٍ ودعم استقرارهم الغذائي وتعزيز روح التكافل في المجتمع خلال شهر رمضان المبارك.',
                'full_description_en'   => 'We provide nutritious meals to those in need and travelers, ensuring food stability and strengthening the spirit of solidarity within the community during the holy month.',
                'type'                  => 'seasonal',
                'status'                => 'active',
                'target_amount'         => 25000000.00,
                'raised_amount'         => 17500000.00,
                'beneficiaries_count'   => 4000,
                'location_ar'           => 'شوارع الخرطوم الرئيسية',
                'location_en'           => 'Main Streets of Khartoum',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2024-03-01',
                'end_date'              => '2024-04-10',
                'is_featured'           => false,
                'is_active'             => true,
                'display_order'         => 3,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 4,
                'category_id'           => $seasonal,
                'title_ar'              => 'توزيع لحوم الأضاحي',
                'title_en'              => 'Qurbani Meat Distribution',
                'short_description_ar'  => 'توفير لحوم الأضاحي للأسر الفقيرة في موسم عيد الأضحى.',
                'short_description_en'  => 'Providing sacrificial meat to poor families during Eid al-Adha.',
                'full_description_ar'   => 'توفير لحوم الأضاحي للأسر الفقيرة في موسم عيد الأضحى، لنشر الفرحة والمساهمة في إحياء الشعائر وتخفيف الأعباء المادية عن الأسر المحتاجة.',
                'full_description_en'   => 'We provide sacrificial meat to poor families during the Eid al-Adha season, spreading joy, honoring the tradition, and easing the financial burden on families in need.',
                'type'                  => 'seasonal',
                'status'                => 'completed',
                'target_amount'         => 45000000.00,
                'raised_amount'         => 45000000.00,
                'beneficiaries_count'   => 2100,
                'location_ar'           => 'عدة ولايات',
                'location_en'           => 'Multiple States',
                'governorate'           => 'كسلا',
                'start_date'            => '2023-06-15',
                'end_date'              => '2023-07-05',
                'is_featured'           => false,
                'is_active'             => true,
                'display_order'         => 4,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 5,
                'category_id'           => $seasonal,
                'title_ar'              => 'كسوة الشتاء',
                'title_en'              => 'Winter Clothing Campaign',
                'short_description_ar'  => 'توزيع الملابس الشتوية والبطانيات على الأسر ذات الدخل المحدود.',
                'short_description_en'  => 'Distributing winter clothes and blankets to low-income families.',
                'full_description_ar'   => 'توزيع الملابس الشتوية والبطانيات على الأسر ذات الدخل المحدود خلال فصل الشتاء، لحمايتهم من البرد القارس وتعزيز شعور الدفء والأمان لدى أطفالهم وكبار السن.',
                'full_description_en'   => 'We distribute winter clothing and blankets to low-income families during the cold season, protecting them from harsh weather and bringing warmth and comfort to children and the elderly.',
                'type'                  => 'seasonal',
                'status'                => 'active',
                'target_amount'         => 30000000.00,
                'raised_amount'         => 12500000.00,
                'beneficiaries_count'   => 1800,
                'location_ar'           => 'أحياء طرفية بالخرطوم',
                'location_en'           => 'Outskirts of Khartoum',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2023-11-01',
                'end_date'              => '2024-01-31',
                'is_featured'           => true,
                'is_active'             => true,
                'display_order'         => 5,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 6,
                'category_id'           => $income,
                'title_ar'              => 'مصادر الدخل الثابتة',
                'title_en'              => 'Fixed Income Sources',
                'short_description_ar'  => 'إطلاق مبادرات مدرة للدخل لتعزيز الاعتماد على الذات في المجتمع.',
                'short_description_en'  => 'Launching income-generating initiatives to strengthen self-reliance in the community.',
                'full_description_ar'   => 'تعزيز الاعتماد على الذات في المجتمع من خلال إطلاق مبادرات مدرة للدخل، مصممة لدعم مهمة المنظمة وتوفير فوائد اقتصادية دائمة للمحتاجين وأسرهم.',
                'full_description_en'   => 'We strengthen community self-reliance by launching income-generating initiatives designed to support the organization mission and provide lasting economic benefits to those in need.',
                'type'                  => 'sustainable',
                'status'                => 'active',
                'target_amount'         => 70000000.00,
                'raised_amount'         => 19000000.00,
                'beneficiaries_count'   => 150,
                'location_ar'           => 'عدة ولايات',
                'location_en'           => 'Multiple States',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2024-01-01',
                'end_date'              => null,
                'is_featured'           => false,
                'is_active'             => true,
                'display_order'         => 6,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
            [
                'id'                    => 7,
                'category_id'           => $training,
                'title_ar'              => 'برنامج التدريب والتطوير',
                'title_en'              => 'Training & Development Program',
                'short_description_ar'  => 'دعم البرامج التدريبية والإنتاجية لتمكين الأفراد وزيادة قدراتهم.',
                'short_description_en'  => 'Supporting training and productivity programs to empower individuals and build capacity.',
                'full_description_ar'   => 'دعم البرامج التدريبية والإنتاجية لتمكين الأفراد وزيادة قدراتهم من خلال فرص تعليمية وتطوير مهاراتهم بشكل مستمر، بما يهيئهم لسوق العمل ويحقق استقلالهم الاقتصادي.',
                'full_description_en'   => 'We support training and productivity programs that empower individuals and build their capacities through continuous learning opportunities, preparing them for the job market and economic independence.',
                'type'                  => 'sustainable',
                'status'                => 'active',
                'target_amount'         => 40000000.00,
                'raised_amount'         => 9000000.00,
                'beneficiaries_count'   => 320,
                'location_ar'           => 'الخرطوم',
                'location_en'           => 'Khartoum',
                'governorate'           => 'الخرطوم',
                'start_date'            => '2024-04-01',
                'end_date'              => null,
                'is_featured'           => false,
                'is_active'             => true,
                'display_order'         => 7,
                'deleted_at'            => null,
                'created_at'            => now(),
                'updated_at'            => now(),
            ],
        ];

        DB::table('projects')->insert($projects);

        // Seed Project Media (Covers)
        $projectMedia = [
            [
                'project_id'    => 1,
                'media_type'    => 'image',
                'url'           => 'https://images.unsplash.com/photo-1594708767771-a7502209ff51?auto=format&fit=crop&w=1200&q=80',
                'caption_ar'    => 'توزيع الحقائب الرمضانية على الأسر المحتاجة',
                'caption_en'    => 'Distributing Ramadan baskets to families in need',
                'is_cover'      => true,
                'display_order' => 1,
            ],
            [
                'project_id'    => 2,
                'media_type'    => 'image',
                'url'           => 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80',
                'caption_ar'    => 'قافلة طبية متنقلة تخدم المجتمعات المحرومة',
                'caption_en'    => 'A mobile medical convoy serving underserved communities',
                'is_cover'      => true,
                'display_order' => 1,
            ],
            [
                'project_id'    => 3,
                'media_type'    => 'image',
                'url'           => 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?auto=format&fit=crop&w=1200&q=80',
                'caption_ar'    => 'وجبات إفطار توزع على عابري السبيل',
                'caption_en'    => 'Iftar meals distributed to travelers',
                'is_cover'      => true,
                'display_order' => 1,
            ],
            [
                'project_id'    => 4,
                'media_type'    => 'image',
                'url'           => 'https://images.unsplash.com/photo-1607346256330-dee7af15f7c5?auto=format&fit=crop&w=1200&q=80',
                'caption_ar'    => 'توزيع لحوم الأضاحي على الأسر المستفيدة',
                'caption_en'    => 'Distributing Qurbani meat to beneficiary families',
                'is_cover'      => true,
                'display_order' => 1,
            ],
            [
                'project_id'    => 5,
                'media_type'    => 'image',
                'url'           => 'https://images.unsplash.com/photo-1608155918314-04a2b1f00889?auto=format&fit=crop&w=1200&q=80',
                'caption_ar'    => 'توزيع الملابس الشتوية والبطانيات',
                'caption_en'    => 'Distributing winter clothes and blankets',
                'is_cover'      => true,
                'display_order' => 1,
            ],
            [
                'project_id'    => 6,
                'media_type'    => 'image',
                'url'           => 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?auto=format&fit=crop&w=1200&q=80',
                'caption_ar'    => 'دعم مشاريع الدخل الثابت للأسر',
                'caption_en'    => 'Supporting fixed income projects for families',
                'is_cover'      => true,
                'display_order' => 1,
            ],
            [
                'project_id'    => 7,
                'media_type'    => 'image',
                'url'           => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
                'caption_ar'    => 'ورشة تدريبية لتمكين الشباب',
                'caption_en'    => 'A training workshop empowering youth',
                'is_cover'      => true,
                'display_order' => 1,
            ],
        ];

        DB::table('project_media')->insert($projectMedia);
    }
}